language: go
go:
        - 1.5.x
        - 1.6.x
        - 1.7.x
        - 1.x
        - tip

install:
        - go get -v ./...
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls

script:
        - go test -v -covermode=count -coverprofile=coverage.out ./...
        - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
