language: go
go:
        - 1.5.x
        - 1.6.x
        - 1.7.x
        - 1.x
        - tip

before_install:
        - go test -v ./...
        - go get github.com/mattn/goveralls

script:
        - $HOME/gopath/bin/goveralls -service=travis-ci
